spring:
  application:
    name: treatment
  datasource:
    url: jdbc:h2:mem:treatment
    username: treatment
    password: treatment
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    hibernate:
      ddl-auto: create
